name: Run test suites
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  RECORD_REPLAY_API_KEY: rwk_67oZlwB0FjMlwawb02pYRB4Fenf0YSD9xIGzQrMEnB3
  DEBUG: pw:browser
  RECORD_REPLAY_VERBOSE: 1

jobs:
  generate-test-run-id:
    name: Generate Test Run ID
    runs-on: ubuntu-latest
    steps:
      - id: uuid
        run: |
          echo "ubuntu-latest-id=$(npx uuid)" >> "$GITHUB_OUTPUT"
          echo "macos-latest-id=$(npx uuid)" >> "$GITHUB_OUTPUT"
          echo "windows-latest-id=$(npx uuid)" >> "$GITHUB_OUTPUT"
    outputs:
      ubuntu-latest: ${{ steps.uuid.outputs.ubuntu-latest-id }}
      macos-latest: ${{ steps.uuid.outputs.macos-latest-id }}
      windows-latest: ${{ steps.uuid.outputs.windows-latest-id }}
  e2etest:
    name: End-to-end tests (${{ matrix.shard }} on ${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    needs: [generate-test-run-id]
    strategy:
      # GH cancels other matrixed jobs by default if one fails. We want all E2E jobs to complete.
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        shard: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Get the yarn cache path.
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: yarn-cache-folder-${{ matrix.platform }}-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: "yarn-cache-folder-"
      # Actually install packages with Yarn
      - name: Install packages
        run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: "update"
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Install Replay Playwright
        run: npx @replayio/playwright install
      - uses: replayio/action-playwright@main
        with:
          command: npx playwright test --shard ${{ matrix.shard }}/10 --reporter=@replayio/playwright/reporter,line tests/*.ts
          working-directory: ./packages/e2e-tests
          api-key: ${{ env.RECORD_REPLAY_API_KEY }}
          public: true
          upload-all: true
          project: replay-chromium
        env:
          REPLAY_PLAYWRIGHT_FIXTURE: 1
          RECORD_REPLAY_METADATA_TEST_RUN_ID: ${{ needs.generate-test-run-id.outputs[matrix.platform] }}
          PLAYWRIGHT_TEST_BASE_URL: https://app.replay.io
          INPUT_STRIPE: ${{ matrix.shard }}/10
          RECORD_REPLAY_TEST_METRICS: 1
          AUTOMATED_TEST_SECRET: ${{ secrets.AUTOMATED_TEST_SECRET }}
          AUTHENTICATED_TESTS_WORKSPACE_API_KEY: ${{ secrets.AUTHENTICATED_TESTS_WORKSPACE_API_KEY }}
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: E2E Tests - ${{ matrix.platform }}
  authenticated-e2etest:
    name: Authenticated end-to-end tests (${{ matrix.shard }} on ${{ matrix.platform }})
    runs-on: ubuntu-latest
    needs: [generate-test-run-id]
    strategy:
      # GH cancels other matrixed jobs by default if one fails. We want all E2E jobs to complete.
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        shard: ["1"]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Get the yarn cache path.
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: "yarn-cache-folder-"
      # Actually install packages with Yarn
      - name: Install packages
        run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: "update"
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Install Replay Playwright
        run: npx @replayio/playwright install
      - uses: replayio/action-playwright@main
        with:
          command: npx playwright test --shard ${{ matrix.shard }}/1 --reporter=@replayio/playwright/reporter,line authenticated/**/*.ts
          working-directory: ./packages/e2e-tests
          api-key: ${{ env.RECORD_REPLAY_API_KEY }}
          public: true
          upload-all: true
          project: replay-chromium
        env:
          REPLAY_PLAYWRIGHT_FIXTURE: 1
          RECORD_REPLAY_METADATA_TEST_RUN_ID: ${{ needs.generate-test-run-id.outputs[matrix.platform] }}
          PLAYWRIGHT_TEST_BASE_URL: https://app.replay.io
          INPUT_STRIPE: ${{ matrix.shard }}/1
          RECORD_REPLAY_TEST_METRICS: 1
          AUTOMATED_TEST_SECRET: ${{ secrets.AUTOMATED_TEST_SECRET }}
          AUTHENTICATED_TESTS_WORKSPACE_API_KEY: ${{ secrets.AUTHENTICATED_TESTS_WORKSPACE_API_KEY }}
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: E2E Tests - ${{ matrix.platform }}
